### PR TITLE
Add pass under empty class

### PR DESCRIPTION
**Pull request by angela-zhao**
Thanks for your contribution!

If you're sending a large PR (e.g., >50 lines),
please open an issue first about the feature / bug, and indicate how you want to contribute.

Before submitting a PR, please run `dev/linter.sh` to lint the code.

See https://detectron2.readthedocs.io/notes/contributing.html#pull-requests
about how we handle PRs.

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
why is this added?

**Comment by angela-zhao** [comment]
> why is this added?

All the functions defined below the class cannot be properly imported without it.

**Comment by ppwwyyxx** [comment]
That does not seem true to me. Could you file a bug with [details](https://github.com/facebookresearch/detectron2/issues/new/choose) if you did run into issues?

**Comment by angela-zhao** [comment]
> That does not seem true to me. Could you file a bug with [details](https://github.com/facebookresearch/detectron2/issues/new/choose) if you did run into issues?

Sorry, I was using an old version. I just cloned the newest version and it works fine. Thanks for your support.

**Pull request closed without merging**
