### PR TITLE
rename in_channels variable used in FPN constructor

### PR DESCRIPTION
**Pull request by nanddalal**
This PR renames the `in_channels` variable used in constructing the FPN.

I found it a bit confusing that we were both enumerating over `in_channels` and assigning each element to a variable also called `in_channels` so at the end of the for loop, `in_channels` would actually be the last element of the original `in_channels` list.

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
I agree it's a bit confusing. Would you maybe rename it to `in_channels_per_feature`? I'm also confused in what `in_channels_idx` means

**Comment by rbgirshick** [comment]
I agree that `in_channels_per_feature` is a better name.

A slightly larger change that I think might be nicer is:

```python
strides = [input_shapes[f].stride for f in in_features]
channels = [input_shapes[f].channels for f in in_features]
...
for stride, in_channels in zip(all_strides, all_channels):
  ...
```

**Comment by ppwwyyxx** [comment]
@nanddalal  could you sign the CLA?

**Comment by nanddalal** [comment]
hi @ppwwyyxx -- yes I am working on it with my company. Thank you both for the PR review!

**Pull request closed without merging**
