### PR TITLE
Pytorch 2.0, Cuda 11.8 and future 12.0 & 12.1 compatible

### PR DESCRIPTION
**Pull request by johnnynunez**
I have been able to compile with CUDA 11.8 and CUDA 12.0 & 12.1 using PyTorch 1.13.1, PyTorch dev 2.0 and python 3.10.6(In local)
- [X] Python <3.8 versions deleted (Deprecated 27 Jun 2023)
- [X] Python 3.10.6 (added as default) (CircleCI images have 3.10.6 & 3.11)
- [X] PyTorch <1.12 delete. Deprecated (https://pytorch.org/blog/deprecation-cuda-python-support/)
- [X] Updated ubuntu-2204:2023.02.1 CPU
- [X] Updated linux-cuda-11:2023.02.1 GPU https://discuss.circleci.com/t/cuda-11-8-gpu-cuda-image-any-plans/47240/3
- [X] New image CircleCI CUDA 11.8, and they are working to CUDA 12. https://discuss.circleci.com/t/cuda-11-8-gpu-cuda-image-any-plans/47240/4
- [X] Windows image 2022: windows-server-2022-gui:2022.10.1
- [X] Updated test compatible with CUDA and PyTorch > 1.10
- [X] Unified workflow GitHub and CircleCI python versions: Python 3.10.6
- [X] Added CUDA variable on CircleCI: You now can select CUDA VERSION.
- [X] Added PyTorch 2.0 and CUDA 11.8. 12.0/12.1 CircleCI (CircleCI working to release CUDA 12 images at the end of the month)
- [X] Fixed tests for PyTorch 1.10+ and Python 3.10
- [X] New versions and lint compatible with Python 3.10 [isort, black, flake8]
image
image

### CODE REVIEW

**Comment by johnnynunez** [comment]
circleci is working now. @wat3rBro @facebook-github-bot

**Comment by johnnynunez** [comment]
circleci is working now. @wat3rBro @ppwwyyxx @facebook-github-bot

**Comment by johnnynunez** [comment]
circleci is working now. @wat3rBro @ppwwyyxx @facebook-github-bot

**Comment by johnnynunez** [comment]
@wat3rBro @ppwwyyxx done! @facebook-github-bot merge

**Comment by johnnynunez** [comment]
@wat3rBro @ppwwyyxx done! @facebook-github-bot merge

**Comment by johnnynunez** [comment]
@wat3rBro @ppwwyyxx done! @facebook-github-bot merge

**Comment by johnnynunez** [comment]
@ppwwyyxx i fixed isort problem in github workflow

**Comment by johnnynunez** [comment]
@facebook-github-bot merge

**Comment by johnnynunez** [comment]
@wat3rBro @ppwwyyxx done! @facebook-github-bot merge

**Comment by johnnynunez** [comment]
@wat3rBro @ppwwyyxx done! @facebook-github-bot merge

**Comment by johnnynunez** [comment]
@ppwwyyxx new version of isort needes double pony -sp . .
So now its fixed

**Comment by johnnynunez** [comment]
@ppwwyyxx linter all repo for python3.10(new recommended python by pytorch and anaconda)

**Comment by johnnynunez** [comment]
@wat3rBro @ppwwyyxx linter all repo for python3.10(new recommended python by pytorch and anaconda)

**Comment by johnnynunez** [comment]
Screenshot 2023-03-13 at 23 43 12
Now is working! @wat3rBro

**Comment by johnnynunez** [comment]
@wat3rBro could you accept github actions, now?

**Comment by johnnynunez** [comment]
Pytorch 2.0 with CPU and CUDA 11.8 added and working.

**Comment by johnnynunez** [comment]
@wat3rBro @ppwwyyxx  Pytorch 2.0 with CPU and CUDA 11.8 added and working.

**Comment by wadhah101** [comment]
Why was this closed ? was it merged ?

**Comment by lijain** [comment]
请问下最新的版本在那可以下载？

**Pull request closed without merging**
