### PR TITLE
add onnxmodel for inference

### PR DESCRIPTION
**Pull request by randombenj**
### Why this change

The idea for this contribution came from this issue: https://github.com/facebookresearch/detectron2/issues/2748

I struggled quite a lot to get onnx inference running (and so did other people according to the issues I found).
Also it is quite hard to get information about this googling and so I lost a few hours of reverse engineering untill
I got inference working correctly. With this contribution, I hope to make ONNX inference a bit easier to get started with.

There are some open things:

- [ ] [get model](https://github.com/facebookresearch/detectron2/compare/master...randombenj:feature/add-onnx-module?expand=1#diff-3c0e5a665a9e83cf602e5b72241e4acee12f1e3a2504193a7f1ba3bc049526edR342) : any way to get the model dynamically
- [ ] [onnx import](https://github.com/facebookresearch/detectron2/compare/master...randombenj:feature/add-onnx-module?expand=1#diff-3c0e5a665a9e83cf602e5b72241e4acee12f1e3a2504193a7f1ba3bc049526edR301) : not sure if this is a good idea
- [ ] [divisibility/device](https://github.com/facebookresearch/detectron2/compare/master...randombenj:feature/add-onnx-module?expand=1#diff-3c0e5a665a9e83cf602e5b72241e4acee12f1e3a2504193a7f1ba3bc049526edR322): any way of getting this dynamically? Will divisibility always be 32?

### Usage

One exampe of how to use this:

```python
# prepare inputs
original_image = cv2.imread('datasets/coco/val2017/000000023937.jpg')

aug = T.ResizeShortestEdge(
    [cfg.INPUT.MIN_SIZE_TEST, cfg.INPUT.MIN_SIZE_TEST], cfg.INPUT.MAX_SIZE_TEST
)

height, width = original_image.shape[:2]
image = aug.get_transform(original_image).apply_image(original_image)
image = torch.as_tensor(image.astype("float32").transpose(2, 0, 1))

inputs = [{"image": image, "height": height, "width": width}]

from detectron2.export import ONNXModel
model = ONNXModel.load_onnx("model.onnx")
outputs = model(inputs)

# visualize results
v = Visualizer(original_image[:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), scale=1.2)
out = v.draw_instance_predictions(outputs[0]["instances"].to("cpu"))
cv2_imshow(out.get_image()[:, :, ::-1])
```

image

### CODE REVIEW

**Comment by randombenj** [comment]
@pieterbl86 You can find how the model was exported in this notebook: https://github.com/randombenj/detectron2onnx-inference/blob/master/detectron2-onnx.ipynb

Its nothing fancy, just a standard model with pretrained weights.

**Comment by pieterbl86** [comment]
> @pieterbl86 You can find how the model was exported in this notebook: https://github.com/randombenj/detectron2onnx-inference/blob/master/detectron2-onnx.ipynb
> 
> 
> 
> Its nothing fancy, just a standard model with pretrained weights.

@randombenj Perfect! I'll give it a try. Thank you for sharing your code!

**Comment by randombenj** [comment]
Any feedback, or shall I close this?

**Comment by randombenj** [comment]
image

**Comment by adithyashankar-97** [comment]
Hi @randombenj Your script supports only for bounding box detections right? Do you have the script for Instance segmentation as well? The ONNXLoad one?

**Comment by randombenj** [comment]
@adithyashankar-97 I don't think it's bound to bounding boxes however you would need to try if it works ... :)

**Comment by Chao86** [comment]
> @pieterbl86 You can find how the model was exported in this notebook: https://github.com/randombenj/detectron2onnx-inference/blob/master/detectron2-onnx.ipynb
> 
> Its nothing fancy, just a standard model with pretrained weights.

Hello, @randombenj , I'm using the API export_onnx  to convert the model to onnx. However, it encounters a RuntimeErroe.[https://github.com/facebookresearch/detectron2/issues/3561#issue-1021583334](url). 
Can you offer some help to tackle this? Thanks in advance.

**Pull request closed without merging**
