### PR TITLE
Add CUDA 11.7 + PyTorch 1.13.0 & nightly support

### PR DESCRIPTION
**Pull request by thiagocrepaldi**
This is a continuation of https://github.com/facebookresearch/detectron2/pull/4205 (Add CUDA 11.3 + PyTorch 1.11.0 and 1.12.1)

@wat3rBro FYI

### CODE REVIEW

**Comment by thiagocrepaldi** [comment]
@ppwwyyxx as discussed at #4205, I am starting a PR for CUDA 11.7

**Comment by johnnynunez** [comment]
Use new image for CircleCI
https://discuss.circleci.com/t/cuda-11-8-gpu-cuda-image-any-plans/47240/4

**Comment by johnnynunez** [comment]
@thiagocrepaldi can you see my pull request? https://github.com/facebookresearch/detectron2/pull/4740

**Comment by thiagocrepaldi** [comment]
@wat3rBro gentle ping

**Comment by thiagocrepaldi** [comment]
@wat3rBro @ppwwyyxx @malfet gentle ping

**Comment by thiagocrepaldi** [comment]
Is this still relevant or should we close it?

**Pull request closed without merging**
