### PR TITLE
Pytorch 2.0, Cuda 11.8 and future 12.0 & 12.1 compatible

### PR DESCRIPTION
**Pull request by johnnynunez**
I have been able to compile with CUDA 11.8 and CUDA 12.0 & 12.1 using PyTorch 1.13.1, PyTorch dev 2.0 and python 3.10.6(In local)
- [X] Python <3.8 versions deleted (Deprecated 27 Jun 2023)
- [X] Python 3.10.6 (added as default) (CircleCI images have 3.10.6 & 3.11)
- [X] PyTorch <1.12 delete. Deprecated (https://pytorch.org/blog/deprecation-cuda-python-support/)
- [X] Updated ubuntu-2204:2023.02.1 CPU
- [X] Updated linux-cuda-11:2023.02.1 GPU https://discuss.circleci.com/t/cuda-11-8-gpu-cuda-image-any-plans/47240/3
- [X] New image CircleCI CUDA 11.8, and they are working to CUDA 12. https://discuss.circleci.com/t/cuda-11-8-gpu-cuda-image-any-plans/47240/4
- [X] Windows image 2022: windows-server-2022-gui:2022.10.1
- [X] Updated test compatible with CUDA and PyTorch > 1.10
- [X] Unified workflow GitHub and CircleCI python versions: Python 3.10.6
- [X] Added CUDA variable on CircleCI: You now can select CUDA VERSION.
- [X] Added PyTorch 2.0 and CUDA 11.8. 12.0/12.1 CircleCI (CircleCI working to release CUDA 12 images at the end of the month)
- [X] Fixed tests for PyTorch 1.10+ and Python 3.10
- [X] New versions and lint compatible with Python 3.10 [isort, black, flake8]
image
image

### CODE REVIEW

**Comment by johnnynunez** [comment]
@ppwwyyxx @wat3rBro @thiagocrepaldi Now, the changes is clearer.

**Comment by LeonidAlekseev** [comment]
up

**Comment by CanKorkut** [comment]
up

**Comment by elvizlai** [comment]
PTAL

**Comment by wadhah101** [comment]
Why this PR is not merged yet ? The current pytorch has some serious vulnerabilities

**Comment by wqh17101** [comment]
Please merge it in.

**Comment by davorvr** [comment]
Hi, I'm getting an error when using this fork which happens while trying to do `import detectron2`, do you know what could be causing this?

```
ImportError: /home/davor/.local/lib/python3.11/site-packages/torch/lib/libgomp-a34b3233.so.1: version `GOMP_5.0' not found (required by /usr/lib/libvtkCommonCore.so.1)
```

**Comment by johnnynunez** [comment]
pytorch 1.12 deleted and updated pytorch 2.0 to 2.01

**Comment by RiccardoMaistri** [comment]
up

**Comment by johnnynunez** [comment]
Added CUDA 12.1 CircleCI image

**Comment by bertsky** [comment]
Great work!

Are there any known backward incompatibilities (requiring reconfiguration or retraining)?

Are you perhaps also going to address any of the following?
- INSTALL.md: update table of prebuilt wheels
- docker/Dockerfile: update versions, maybe drop `nvidia/cuda` base image (as Pytorch does not use apt packages for CUDA and cuDNN anyway)
- #4472  (i.e. fixing source distribution for platforms not covered by wheels, and adding torch as an overt dependency)

**Comment by johnnynunez** [comment]
> > Great work!
> > Are there any known backward incompatibilities (requiring reconfiguration or retraining)?
> > Are you perhaps also going to address any of the following?
> > 
> > * INSTALL.md: update table of prebuilt wheels
> > * docker/Dockerfile: update versions, maybe drop `nvidia/cuda` base image (as Pytorch does not use apt packages for CUDA and cuDNN anyway)
> > * [setup.py treats torch as a setup-time dependency #4472](https://github.com/facebookresearch/detectron2/issues/4472)  (i.e. fixing source distribution for platforms not covered by wheels, and adding torch as an overt dependency)
> 
> I'm not from Meta so I don't have access from links. But I updated the Install.md. @ppwwyyxx @facebook-github-bot merge it. It generates artifacts from macOS, Linux automatically.
> 
> Why do you need docker here? It should be in another PR

do you mean this?
image

**Comment by bertsky** [comment]
> Why do you need docker here? It should be in another PR

Yes, maybe off-topic. But if it's not too much work, would be great to update as well (currently trying myself, will perhaps make a differential PR)

> do you mean this?

Not quite. Since Pytorch (esp. the CUDA releases) may need a different index, and the `dependency_links` mechanism of setuptools has been dropped for good, I don't know how to cover this correctly. But in the very least, one would need to avoid the `import torch` statements further up in setup.py.

**Comment by johnnynunez** [comment]
> 

 for cuda releases you need extra index url

**Comment by ZekunZh** [comment]
Up, @ppwwyyxx could you please approve and merge this PR ?

**Comment by janzd** [comment]
Could you please explain how to install using your wheels? Or if you have any installation instructions anywhere, could you send a link to it?

**Comment by johnnynunez** [comment]
> Could you please explain how to install using your wheels? Or if you have any installation instructions anywhere, could you send a link to it?

download it and pip install name.whl

**Comment by danieltudosiu** [comment]
Any update on this?

**Comment by mac6894** [comment]
hi, I am using Ubuntu 22.04, CUDA 12.3, and would like to install detectron2. I did "python3 -m pip install 'git+https://github.com/johnnynunez/detectron2.git' ", but, I still get this runtime error: 

"RuntimeError:
      The detected CUDA version (12.3) mismatches the version that was used to compile
      PyTorch (11.7). Please make sure to use the same CUDA versions.
      
      [end of output]"

Do you know how I can fix this? Thanks.

**Comment by johnnynunez** [comment]
> hi, I am using Ubuntu 22.04, CUDA 12.3, and would like to install detectron2. I did "python3 -m pip install 'git+https://github.com/johnnynunez/detectron2.git' ", but, I still get this runtime error:
> 
> "RuntimeError: The detected CUDA version (12.3) mismatches the version that was used to compile PyTorch (11.7). Please make sure to use the same CUDA versions.
> 
> ```
>   [end of output]"
> ```
> 
> Do you know how I can fix this? Thanks.

First install pytorch:

pip3 install -U torch torchvision torchaudio

**Comment by CQHofsns** [comment]
Hi @johnnynunez 

I am using Ubuntu server, CUDA 12.2, torch-2.3.1 torchaudio-2.3.1 torchvision-0.18.1. However, when I try to follow the guide in the installation tutorial I get this error:

> Collecting git+https://github.com/facebookresearch/detectron2.git
>   Cloning https://github.com/facebookresearch/detectron2.git to /tmp/pip-req-build-eb1t5q_j
>   Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /tmp/pip-req-build-eb1t5q_j
>   Resolved https://github.com/facebookresearch/detectron2.git to commit 70f454304e1a38378200459dd2dbca0f0f4a5ab4
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [20 lines of output]
>       Traceback (most recent call last):
>         File "/path/to/project/.env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/path/to/project/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/path/to/project/.env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>                  ^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-2qctbu22/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=[])
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-2qctbu22/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
>           self.run_setup()
>         File "/tmp/pip-build-env-2qctbu22/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
>           super().run_setup(setup_script=setup_script)
>         File "/tmp/pip-build-env-2qctbu22/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
>           exec(code, locals())
>         File "<string>", line 10, in <module>
>       ModuleNotFoundError: No module named 'torch'
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

Does this mean Detectron not work on CUDA 12.2? Is there any workaround?

Thanks

**Comment by johnnynunez** [comment]
> Hi @johnnynunez
> 
> I am using Ubuntu server, CUDA 12.2, torch-2.3.1 torchaudio-2.3.1 torchvision-0.18.1. However, when I try to follow the guide in the installation tutorial I get this error:
> 
> > Collecting git+https://github.com/facebookresearch/detectron2.git
> > Cloning https://github.com/facebookresearch/detectron2.git to /tmp/pip-req-build-eb1t5q_j
> > Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /tmp/pip-req-build-eb1t5q_j
> > Resolved https://github.com/facebookresearch/detectron2.git to commit [70f4543](https://github.com/facebookresearch/detectron2/commit/70f454304e1a38378200459dd2dbca0f0f4a5ab4)
> > Installing build dependencies ... done
> > Getting requirements to build wheel ... error
> > error: subprocess-exited-with-error
> > × Getting requirements to build wheel did not run successfully.
> > │ exit code: 1
> > ╰─> [20 lines of output]
> > Traceback (most recent call last):
> > File "/path/to/project/.env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in 
> > main()
> > File "/path/to/project/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
> > json_out['return_val'] = hook(**hook_input['kwargs'])
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/path/to/project/.env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
> > return hook(config_settings)
> > ^^^^^^^^^^^^^^^^^^^^^
> > File "/tmp/pip-build-env-2qctbu22/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
> > return self._get_build_requires(config_settings, requirements=[])
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/tmp/pip-build-env-2qctbu22/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
> > self.run_setup()
> > File "/tmp/pip-build-env-2qctbu22/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
> > super().run_setup(setup_script=setup_script)
> > File "/tmp/pip-build-env-2qctbu22/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
> > exec(code, locals())
> > File "", line 10, in 
> > ModuleNotFoundError: No module named 'torch'
> > [end of output]
> > note: This error originates from a subprocess, and is likely not a problem with pip.
> > error: subprocess-exited-with-error
> > × Getting requirements to build wheel did not run successfully.
> > │ exit code: 1
> > ╰─> See above for output.
> > note: This error originates from a subprocess, and is likely not a problem with pip.
> 
> Does this mean Detectron not work on CUDA 12.2? Is there any workaround?
> 
> Thanks

it is working, you only have to compile it

**Comment by nitinmukesh** [comment]
I am trying to download wheel for Windows
https://dl.fbaipublicfiles.com/detectron2/wheels/cu117/torch1.13.1/index.html

Coming with Access denied error

**Comment by oximi123** [comment]
> > Could you please explain how to install using your wheels? Or if you have any installation instructions anywhere, could you send a link to it?
> 
> download it and pip install name.whl

Hi, where is the link for downloading your wheel? Thanks!

**Comment by jrm-stuhilton** [comment]
The link https://bootstrap.pypa.io/pip/3.10/get-pip.py no longer exists.

**Pull request closed without merging**
