### PR TITLE
Added support for smaller ResNet blocks 

### PR DESCRIPTION
**Pull request by RaymondKirk**
Added support for ResNet-18 and ResNet-34 blocks. Example config change:

```yaml 
MODEL:
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
```

### CODE REVIEW

**Comment by startupgurukul** [comment]
If any buildbot exists, Pre-trained models would be super awesome.

**Comment by RaymondKirk** [comment]
I've converted the official pytorch ResNet models to detectron2 format, which I can upload if not, but an official build would be great!

**Comment by RaymondKirk** [comment]
Closed this PR due to inactivity.

**Comment by ppwwyyxx** [comment]
Sorry for not noticing this. If you are still interested to contribute, I can provide some feedbacks on the changes that need to be addressed.

**Pull request closed without merging**
