### PR TITLE
Add batch predictor 

### PR DESCRIPTION
**Pull request by sailist**
It's not very convenient when do batch inference by using original detectron2 api, the solution provided here https://github.com/facebookresearch/detectron2/issues/282#issuecomment-737270926 is good, and I extended it's code to support more forms.

### CODE REVIEW

**Comment by ashnair1** [comment]
@sailist Have you tried using this BatchPredictor with AsyncPredictor?

**Comment by sailist** [comment]
Fine, I'll try it, thanks.

**Comment by Sorakuhaku** [comment]
Can you add unit test to ensure it is working properly?

**Comment by ppwwyyxx** [comment]
As the doc of DefaultPredictor mentions, it is only for simple demo purposes and we do not plan to extend it with new capabilities. Users are expected to use the `model` object following its formats (which supports batch predictions) if more complicated logic is needed.

**Pull request closed without merging**
