### PR TITLE
setup.py : missing fvcore

### PR DESCRIPTION
**Pull request by jeremyfix**
I was missing fvcore (provided by FAIR)  when pip installing detectron2.

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
Thanks for the fix. Could you also remove the mention of fvcore from https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md#requirements, since it will now be automatically installed?

**Comment by jeremyfix** [comment]
@ppwwyyxx done.

**Comment by ppwwyyxx** [comment]
I confirmed that the URL syntax is not supported when running `setup.py` directly (e.g., `python setup.py install`) -- it still searches on pypi instead. I'll revert this change. Feel free to follow up with new PRs if you found the correct syntax for it.

**Comment by jeremyfix** [comment]
You are right ; I gave a try in a [Dockerfile](https://github.com/jeremyfix/detectron2/blob/dockerfileCPU/Dockerfile.cpu) (a CPU dockerfile for this test) and `pip install -e`  works but `python3 setup.py install` fails with a "couldn't find index page...." ; I will have a look to see if I can fix this.

**Comment by jeremyfix** [comment]
@ppwwyyxx :  I think this is is fixed with an example [Dockerfile](https://github.com/jeremyfix/detectron2/blob/dockerfileCPU/Dockerfile.cpu) to be tested on CPU. 
```
git clone https://github.com/jeremyfix/detectron2
cd detectron2
git checkout dockerfileCPU
docker build -t detectron2:cpuv0 -f Dockerfile.cpu .
docker run -it detectron2:cpuv0
sh test.sh
```
And then you can comment/uncomment  in Dockerfile.cpu  to use `pip install -e`


This is still a kind of black magic for me, I'm not familiar enough with the setuptools and pip installations; But it seems that for `setup.py install` to be working, the git links need to be specified in the dependency_links ; These dependency_links are deprecated for [pip install](https://setuptools.readthedocs.io/en/latest/setuptools.html#dependencies-that-aren-t-in-pypi) but that does not seem to be an issue. This way, you can install both using `pip install -e` or `python3 setup.py install`

After some cleanup, keeping only the modified setup.py , does it make sense to create a new pull request ?

**Comment by ppwwyyxx** [comment]
Thanks for digging into this. We would appreciate a new PR!

**Pull request closed without merging**
