### PR TITLE
Support empty predictions when visualizing results

### PR DESCRIPTION
**Pull request by c1aris**
This PR fixes a potential error when no predictions found in `tools/visualize_json_results.py`.

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
What is the error without this PR?

**Comment by c1aris** [comment]
The `BoxMode.convert` method would raise an IndexError when the shape of `bbox` becomes `(0,)`, which may be caused by empty prediction or all the confidences are below `conf_threshold`.

Besides, maybe checking the shape of `chosen` instead of `score` is more reasonable, I'll create one more commit to fix that.

Sorry but I can not reproduce the bug because I've deleted the json file by mistake.

**Comment by ppwwyyxx** [comment]
Does it work if you add `bbox = bbox.reshape(-1, 4)` to make it a ndarray of shape (0, 4) ?
It's reasonable to expect `BoxMode.convert` to produce a (0, 4) array when the input shape is (0, 4). If that's not working we can get it fixed.

**Comment by c1aris** [comment]
Yes it works after reshaping `bbox`. I've tested it by using another json file and setting `conf_threshold` to 2.0. Thanks for your suggestion.

**Pull request closed without merging**
