### PR TITLE
upgrade docker image from 18.04 to 20.4

### PR DESCRIPTION
**Pull request by farukcankaya**
Fixes https://github.com/facebookresearch/detectron2/issues/4394 https://github.com/facebookresearch/detectron2/issues/4335 by upgrading docker image from 'nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04'  to 'nvidia/cuda:11.1.1-cudnn8-devel-ubuntu**20.04**' . This assumes cuda compatibility problem reported in https://github.com/facebookresearch/detectron2/issues/3524 is fixed. I'm able to build detection with ubuntu20.4 successfully. However, I couldn't run all tests since I don't have resources now. If the problem still continues, you can ignore this PR. I've created another PR that doesn't change the docker image but upgrades the Python inside it: https://github.com/facebookresearch/detectron2/pull/4405

### CODE REVIEW

**Comment by vogelbam** [comment]
This worked for me, however, to be able to run the training scripts I had to downgrade `setuptools` to version 59.2.0 as suggested in https://github.com/pytorch/pytorch/issues/69894.

**Comment by ppwwyyxx** [comment]
Unless someone verifies it, I strongly doubt that the issue in #3524 still exists.

**Comment by vogelbam** [comment]
This PR can only fix the issue about the base Dockerfile (https://github.com/facebookresearch/detectron2/issues/4394, https://github.com/facebookresearch/detectron2/issues/4335). The deploy Dockerfile still fails due to the issue mentioned above (https://github.com/facebookresearch/detectron2/issues/3524), even after updating the `CMAKE_PREFIX_PATH` accordingly.

**Comment by Robotatron** [comment]
Does not work:

```
Dockerfile:3
--------------------
   1 |     # official and updated det2 docker
   2 |     
   3 | >>> FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04
   4 |     # use an older system (18.04) to avoid opencv incompatibility (issue#3524)
   5 |     
--------------------
ERROR: failed to solve: failed to register layer: Error processing tar file(exit status 1): write /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcufft_static_nocallback.a: no space left on device
(base) jupyter@yolact-eu-for-object-detection-1:~/detectron2_detection/detectron2/docker$ 
```

**Comment by Robotatron** [comment]
@ppwwyyxx I think this issue is still unresolved + the docker file from this repo does not work, I tried it yesterday. Any reason to close this?

**Pull request closed without merging**
