### PR TITLE
Add unit test for PointRend ONNX export

### PR DESCRIPTION
**Pull request by thiagocrepaldi**
Fixes https://github.com/pytorch/pytorch/issues/69674

Refer to projects/PointRend/configs/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco.yaml

### CODE REVIEW

**Comment by thiagocrepaldi** [comment]
@ppwwyyxx @mcimpoi This PR adds a sample for a model asked in PyTorch repo

**Comment by thiagocrepaldi** [comment]
@ppwwyyxx @mcimpoi Could you review this one when you have some time? Thanks

**Comment by thiagocrepaldi** [comment]
> @ppwwyyxx @mcimpoi Could you review this one when you have some time? Thanks

gentle ping

**Comment by thiagocrepaldi** [comment]
@wat3rBro Could you review this one when you have some time? Thanks

**Comment by thiagocrepaldi** [comment]
> > @ppwwyyxx @mcimpoi Could you review this one when you have some time? Thanks
> 
> gentle ping

Rebasing to allow up-to-date review

**Comment by thiagocrepaldi** [comment]
@ppwwyyxx @mcimpoi @wat3rBro gentle ping

**Review by malfet — APPROVED** [review]

**Comment by thiagocrepaldi** [comment]
@wat3rBro could you take a quick look at this?

**Comment by thiagocrepaldi** [comment]
@wat3rBro could you take a quick look into this one? I am trying to clean the detectron2 PRs pipeline and this one is fairly simple, it is approved and keeps conflicting with other PRs because they add tests to the same file

**Comment by thiagocrepaldi** [comment]
@wat3rBro gentle ping

**Comment by thiagocrepaldi** [comment]
@ppwwyyxx @wat3rBro gentle ping

**Comment by thiagocrepaldi** [comment]
@ppwwyyxx @wat3rBro gentle ping

**Pull request closed without merging**
