### PR TITLE
Remove black version constraint, except for dev dependencies

### PR DESCRIPTION
**Pull request by lpasselin**
fix https://github.com/facebookresearch/detectron2/issues/4005

Currently, having a requirements.txt containing detectron2 and a specific version of black is conflicting.

````
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
detectron2 0.6+cu113 requires black==21.4b2, but you have black 22.3.0 which is incompatible.
````

This PR moves the strict black version to dev dependencies
It also removes the version specification for the regular dependencies.

detectron2 does require a specific version of black for development. 
detectron2 does **not** require a specific at runtime since only `black.format_str` is used. This function is available in all versions of black (even in the pre-release versions).

### CODE REVIEW

**Review by ppwwyyxx — APPROVED** [review]

**Comment by wat3rBro** [comment]
I don't know why changing the requirement of `black` also changes `protobuf` version, which causes CI failing. We need to "downgrade protobuf package to 3.20.x or lower".

**Comment by ppwwyyxx** [comment]
The protobuf problem is caused by the recent protobuf release https://github.com/protocolbuffers/protobuf/issues/10051. 
Setting an env var like in https://github.com/facebookresearch/detectron2/commit/1f7fa2c9a0cc85f6b938303dbbd794087e314552 can fix the issue (CI passes there)

**Comment by ppwwyyxx** [comment]
I took the liberty to add the protobuf fix to @lpasselin 's branch. @wat3rBro could you merge this?

**Comment by lpasselin** [comment]
@wat3rBro is there anything I can do to help you merge this?

**Comment by samwaterbury** [comment]
I would love to get this merged. I consider this a bug — including a formatter in the installation requirements is a packaging mistake, and it makes `detectron2` harder to use.

@wat3rBro can this be merged?

**Comment by ppwwyyxx** [comment]
Fixed in #4678

**Pull request closed without merging**
