### PR TITLE
allow convert_to_coco_dict for custom dataset without annotations

### LINKED ISSUE #1684: (coco-style) Inference fails for custom dataset without annotations
When testing for a custom dataset without annotations, it would fail to convert to coco dict.

### PR DESCRIPTION
**Pull request by wangg12**
Fix #1684 . Allowing inference when annotations are not available for custom datasets.

### CODE REVIEW

**Comment by wangg12** [comment]
Fix #1684

**Comment by ppwwyyxx** [comment]
Please describe the problem first. Currently, the issue is empty.

**Comment by wangg12** [comment]
I think the issue already describes the problem clearly:)

**Comment by ppwwyyxx** [comment]
An easier solution is to let `convert_to_coco_json` support dataset without annotations (instead of throwing an error). That should be doable with <5 lines.

**Comment by wangg12** [comment]
Maybe using
```
anns_per_image = image_dict.get("annotations", [])
```
in https://github.com/facebookresearch/detectron2/blob/master/detectron2/data/datasets/coco.py#L321.
I'm not sure if this is sufficient.

**Comment by wangg12** [comment]
I tested this, it works for me by just changing one line.

**Comment by ppwwyyxx** [comment]
Not sure whether https://github.com/facebookresearch/detectron2/blob/e45cd680d52569494ea2110fbd2ec3d6b48a5af9/detectron2/data/datasets/coco.py#L398 needs to be changed as well, given this line in evaluator:
https://github.com/facebookresearch/detectron2/blob/e45cd680d52569494ea2110fbd2ec3d6b48a5af9/detectron2/evaluation/coco_evaluation.py#L86

**Comment by wangg12** [comment]
By doing this, the evaluation will still be performed. But got all nan results.

**Comment by wangg12** [comment]
Now it should be fine. If there are no annotations at all, the converted coco json file will not contain `"annotations"`.

**Pull request closed without merging**
