### PR TITLE
make fairscale optional dependency

### LINKED ISSUE #4005: Update black to 22.1.0
## 🚀 Feature

Update black, the code formatter, to version 22.1.0.
I've already did the changes over here: https://github.com/facebookresearch/detectron2/compare/main...BruegelN:update-black

## Motivation & Examples

Version 22.1.0 is the first stable release of black: https://github.com/psf/black/releases/tag/22.1.0

With this version they provide a [stability policy](https://black.readthedocs.io/en/latest/the_black_code_style/index.html#stability-policy).

## Note

When including detectron2 into another project which is also using black it's nice to share the same (stable) version of black. The fist non-beta release of black is most likely used by some projects or they're willing to upgrade.

BUT: Updating black will also include a huge diff due to the changed codestyle guidelines: https://github.com/BruegelN/detectron2/commit/844538858bb6867a78e49d128346732d5cc3ea0d
I've already did all the required changes over here: https://github.com/facebookresearch/detectron2/compare/main...BruegelN:update-black

I'm aware this is an opinionated proposal, please let me know what you think.

### PR DESCRIPTION
**Pull request by ppwwyyxx**
Make fairscale optional. It's used rarely and has caused people to report installation issues before such as #4550. Getting fairscale to work in my environment is also nontrivial so it would be good if it's optional.

Remove constraints on black version (fix #4005).

### CODE REVIEW

**Review by wat3rBro — APPROVED** [review]
thanks for updating

**Comment by ppwwyyxx** [comment]
@wat3rBro friendly ping :smile:

**Review by wat3rBro — APPROVED** [review]

**Comment by wat3rBro** [comment]
@ppwwyyxx I haven't found the button to import it to fbsource, are you able to merge it from your side?

**Comment by ppwwyyxx** [comment]
I have no idea.. does other meta projects work?

IIRC there should be a git branch named "shipit" or something that contains config files for import, but I cannot find it (or perhaps it's not public).

**Comment by wat3rBro** [comment]
I found it on chrome (it perhaps requires some browser extensions).

**Pull request closed without merging**
