### PR TITLE
Max to keep

### PR DESCRIPTION
**Pull request by tfurmston**
Hi, 

This PR addresses the issue discussed in this [issue](https://github.com/facebookresearch/detectron2/issues/1803).

I've not added any tests, but happy to do so if it is felt necessary.

### CODE REVIEW

**Comment by tfurmston** [comment]
The CI keeps failing on what seems to be an issue unrelated to my PR. Also, it seems to happen sporadically on `ci/circleci: linux_gpu_tests_pytorch1.4`, `ci/circleci: linux_gpu_tests_pytorch1.5` & `ci/circleci: linux_gpu_tests_pytorch1.6`. 

Are this stages in CI known to be flaky? Or is it something related to the PR?

Thanks

**Comment by bencwallace** [comment]
What's the status of this PR?

**Comment by tfurmston** [comment]
I did the update. However, CI kept dying for an unrelated reason. 

I was originally waiting for a response on the issue, but It's been a while now. Maybe I should update and try again.

**Comment by ppwwyyxx** [comment]
As mentioned in https://github.com/facebookresearch/detectron2/blob/bbdee4cf6bc100fedad7cfad3225bb1da12fa175/detectron2/config/defaults.py#L4-L6 we have stopped adding new features to CfgNode.

`max_to_keep` is an argument of checkpointer, therefore the new config system supports it automatically. In fact the example uses it:
https://github.com/facebookresearch/detectron2/blob/bbdee4cf6bc100fedad7cfad3225bb1da12fa175/configs/common/train.py#L1-L18

**Pull request closed without merging**
