### PR TITLE
add apex fp16 trainer

### PR DESCRIPTION
**Pull request by lbin**
first row: copy from model zoo
second row: our results, 8x2080Ti
faster rcnn
lr sched 3x 
| Name | train time(s/iter)|infer time(s/im)|train mem(GB)|box AP|
|:------:|:------:|:------:|:------:|:------:|
|R50-FPN|0.209|0.047|3.0|40.2|
|R50-FPN-Apex|0.326|0.051|2.8|40.1|

RetineNet
lr sched 3x 
| Name | train time(s/iter)|infer time(s/im)|train mem(GB)|box AP|
|:------:|:------:|:------:|:------:|:------:|
|R50|0.201|0.063|3.9|37.9|
|R50-Apex|0.258|0.077|3.3|38.3|

Mask R-CNN
lr sched 3x 
| Name | train time(s/iter)|infer time(s/im)|train mem(GB)|box AP|mask AP|
|:------:|:------:|:------:|:------:|:------:|:------:|
|R50-FPN|0.261|0.055|3.4|41.0|37.2|
|R50-FPN-Apex|0.388|0.057|3.3|40.9|37.2|

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
Could you share some numbers of speed, memory and accuracy of fp16 training under the same config (same batch size, etc)?

Could you also test Faster R-CNN as well? R-CNNs are more frequently used but I suppose it needs more effort to work with fp16.

**Comment by lbin** [comment]
I will try these later~

**Comment by lbin** [comment]
@ppwwyyxx  How to generate model id?

**Comment by lbin** [comment]
> @ppwwyyxx How to generate model id?

> The model id column is provided for ease of reference. To check downloaded file integrity, any model on this page contains its md5 prefix in its file name.

**Comment by ppwwyyxx** [comment]
You don't need to update model zoo for experiments you run. Although we'd like to know about your experiments (and rerun them when we're merging the PR) to better understand how well the PR is working.

**Comment by lbin** [comment]
@ppwwyyxx 
I got some very strange results, retinanet 3x for example:
After train last epoch, I got very low mAP:

|  AP   |  AP50  |  AP75  |  APs   |  APm   |  APl  |
|:-----:|:------:|:------:|:------:|:------:|:-----:|
| 7.854 | 10.462 | 8.704  | 15.459 | 26.316 | 9.461 |

but if I use --eval-only MODEL.WEIGHTS output/model_final.pth for eval only, I got good results:

|   AP   |  AP50  |  AP75  |  APs   |  APm   |  APl   |
|:------:|:------:|:------:|:------:|:------:|:------:|
| 38.283 | 58.245 | 40.911 | 22.799 | 41.947 | 50.211 |

Did you meet these bugs?

P.S. faster and mask also got same bug.

**Comment by ppwwyyxx** [comment]
I suppose some inference logic in RetinaNet are not correctly handled by amp. 
Amp patches the model in some quite hacky ways so I would not be surprised if it doesn't work out-of-the-box on a complicated model. I think you can start debugging by making the inference float32 only.

**Comment by lbin** [comment]
I will do more experiments and reopen this pr~

**Comment by lbin** [comment]
> Hi, any update on this? Any plan to merge? Thanks.
@cognitiveRobot 
refer: https://github.com/facebookresearch/detectron2/pull/925

**Pull request closed without merging**
