### PR TITLE
add apex trainer example project

### PR DESCRIPTION
**Pull request by lbin**
#72 
We Create a ApexTrainer based on SimpleTrainer, so we could use much more batch size, for example, in retinanet_r50, we could use 32 and got 36.7( box AP)

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
Thanks for the PR! After a quick look it seems like a pretty nice addition to me. I'll have time to look at it more thoroughly some time next week.

**Comment by blueardour** [comment]
@lbin Hi, Thanks for the great contribution.

I recently also focused in the FP16 training. After checking your code, it seemed that only the amp.initialize and amp.scale_loss APIs are employed. With my experience in image classification scenario, the DistributedDataParallel should also be replaced by from apex.parallel import DistributedDataParallel as DDP. However, I noticed you comment out line 75 in apex_trainer.py. Is there any reason why not using the amp DDP?

**Comment by soldierofhell** [comment]
@blueardour, NVIDIA doesn't recommend to use their DDP anymore, see e.g. https://github.com/NVIDIA/apex/tree/master/examples/imagenet#distributed-training

Has anyone tried to patch [Mask X152](https://github.com/facebookresearch/detectron2/blob/master/configs/Misc/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml) model. I did it (by forcing roialign and deconv to 32 bit) but unfortunately see no memory gains in opt_level=O1 (O2 doesn't work at all)?

**Comment by soldierofhell** [comment]
@ppwwyyxx, @lbin as for the PR I think it would be better to integrate apex (as an option) in current trainers classes. Creating separete class for 3 lines of code will lead to unnecessary maintenance for apex trainer class

**Comment by lbin** [comment]
@soldierofhell this is an example project for detectron2, not only for fp16 or apex, your suggestion is my next step.

**Comment by sharathts** [comment]
@lbin I notice that training with AMP matches the fp32 loss curve. But evaluating aafter training gives me bad mAP (~9). Reevaluating on amp saved checkpoint gives me good mAP. 

Did you encounter anything similar?

**Comment by lbin** [comment]
> @lbin I notice that training with AMP matches the fp32 loss curve. But evaluating aafter training gives me bad mAP (~9). Reevaluating on amp saved checkpoint gives me good mAP.
> 
> Did you encounter anything similar?

@sharathts you should try this https://github.com/facebookresearch/detectron2/pull/925

**Comment by CarryHJR** [comment]
@lbin in your commit, I find there isn't any code changes during saving model, in my experience, it seems we need extra codes when saving model

**Comment by batrlatom** [comment]
I tried your apex code with maskrcnn, but it needs more research. I am getting errors. Do you know how to modify maskrcnn yaml file to make it work ( https://github.com/facebookresearch/detectron2/blob/master/configs/Base-RCNN-FPN.yaml ) ?

**Pull request closed without merging**
